In [1]:
import petthermotools as ptt 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

#### uncomment these two lines if alphaMELTS files are not added to your Python path - obviously you're have to change the file location
# import sys
# sys.path.append(r"/Users/gleesonm/Library/CloudStorage/GoogleDrive-gleesonm@berkeley.edu/My Drive/2022/GitHub/MELTS130beta/MacOS")

alphaMELTS for Python files successfully located.
If using the Green et al. (2025) or Weller et al. (2024) thermodynamic models please run `ptt.activate_petthermotools_env()` prior to any calculations.

In [2]:
ptt.activate_petthermotools_env()

Julia environment detected.
Initializing MAGEMin environment and workers...

/Users/gleesonm/anaconda3/lib/python3.11/site-packages/juliacall/__init__.py:61: UserWarning: torch was imported before juliacall. This may cause a segfault. To avoid this, import juliacall before importing torch. For updates, see https://github.com/pytorch/pytorch/issues/78829.
  warnings.warn(

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

  Activating project at `~/.petthermotools_julia_env`
  Activating project at `~/.petthermotools_julia_env`

      From worker 2:	  Activating project at `~/.petthermotools_julia_env`
      From worker 3:	  Activating project at `~/.petthermotools_julia_env`
      From worker 5:	  Activating project at `~/.petthermotools_julia_env`
      From worker 4:	  Activating project at `~/.petthermotools_julia_env`
Using libMAGEMin.dylib from MAGEMin_jll
Using libMAGEMin.dylib from MAGEMin_jll

Precompiling MAGEMinCalc...
    564.3 ms  ? PythonCall
Info Given MAGEMinCalc was explicitly requested, output will be shown live
Using libMAGEMin.dylib from MAGEMin_jll
┌ Warning: Module PythonCall with build ID fafbfcfd-5919-c725-0476-cd0238baa5be is missing from the cache.
│ This may mean PythonCall [6099a3de-0909-46bc-b1f4-468b9a2dfc0d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:2541
   1122.2 ms  ? MAGEMinCalc
[ Info: Precompiling MAGEMinCalc [dd69d18c-a947-4316-a873-d8ea006ff1b2] (cache misses: wrong dep version loaded (4), incompatible header (4), mismatched flags (2))
┌ Warning: Module PythonCall with build ID fafbfcfd-5919-c725-0476-cd0238baa5be is missing from the cache.
│ This may mean PythonCall [6099a3de-0909-46bc-b1f4-468b9a2dfc0d] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:2541
┌ Info: Skipping precompilation due to precompilable error. Importing MAGEMinCalc [dd69d18c-a947-4316-a873-d8ea006ff1b2].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.

      From worker 3:	Using libMAGEMin.dylib from MAGEMin_jll
      From worker 4:	Using libMAGEMin.dylib from MAGEMin_jll
      From worker 5:	Using libMAGEMin.dylib from MAGEMin_jll
      From worker 2:	Using libMAGEMin.dylib from MAGEMin_jll
Julia Environment Ready. MAGEMinCalc v0.6.3 detected
Julia Environment and Workers Ready.

In [5]:
# used to suppress MELTS outputs in MacOS systems (run twice)
import platform
if platform.system() == "Darwin":
    import sys
    import os
    sys.stdout = open(os.devnull, 'w')
    sys.stderr = open(os.devnull, 'w')

In [6]:
bulk = {'SiO2': 53.93,
        'TiO2': 0.67,
        'Al2O3': 18.56,
        'FeOt': 8.5,
        'MnO': 0.21,
        'MgO': 3.96,
        'CaO': 9.16,
        'Na2O': 2.92,
        'K2O': 0.69,
        'P2O5': 0.13}

In [7]:
Combined = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, # small bug, you have to make sure T_C is the correct size
                      P_bar = 2000, H2O_init = np.random.random(100)*10,
                      fO2_buffer="NNO", fO2_offset = 1)

In [8]:
Combined['liquid1']

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,Cr2O3_Liq,Fe2O3_Liq,FeO_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq
0,54.050251,0.522789,18.067847,0.0,1.637433,3.833884,5.307235,0.210468,3.633841,9.180425,2.926511,0.691539,0.130290,5.114723,0.0,0.277612
1,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
2,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
3,64.060197,0.862673,13.752590,0.0,1.688352,3.909566,5.428734,0.527364,2.550808,6.706250,2.833093,1.467787,0.326463,1.314856,0.0,0.279838
4,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
96,54.863545,0.542544,18.060566,0.0,1.663093,3.864562,5.361002,0.216203,3.721156,9.185595,2.983534,0.709760,0.133840,4.055603,0.0,0.279134
97,53.901299,0.518649,18.022649,0.0,1.632864,3.829529,5.298769,0.209888,3.625127,9.155125,2.918446,0.689633,0.129931,5.366859,0.0,0.277279
98,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
99,63.408746,0.821036,14.000949,0.0,1.704407,3.938528,5.472142,0.490531,2.710369,6.775342,2.959419,1.398451,0.303662,1.488561,0.0,0.280258

## Run the same calculation but suppress ALL solids (random H2O and CO2 contents)

In [9]:
NoSolids = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, P_bar = 500, H2O_Liq = np.random.random(100)*10, 
                                 CO2_Liq = np.random.random(100)*0.4, fO2_buffer = "NNO", fO2_offset = 1, Suppress = "All")

In [10]:
NoSolids['All'].head()

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),dVdP_cm^3/bar,mass_g_Liq,...,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq,H2O_Fl,CO2_Fl,X_H2O_mol_Fl,X_CO2_mol_Fl
0,1070.0,500.0,100.265360,-1.260581e+06,272.429424,44.023651,2277.533961,-8.200846,0.003193,99.799424,...,2.896604,0.684472,0.128958,1.787944,0.007209,0.283209,53.455223,46.544777,0.737351,0.262649
1,1070.0,500.0,100.259744,-1.257668e+06,288.125223,63.705166,1573.808675,-8.200846,0.020721,98.106503,...,2.887318,0.682277,0.128545,2.108574,0.001698,0.282906,86.326811,13.673189,0.939148,0.060852
2,1070.0,500.0,100.269403,-1.262687e+06,263.086646,39.598250,2532.167512,-8.200846,0.000074,100.199401,...,2.920671,0.690158,0.130030,0.960198,0.018262,0.284016,13.309094,86.690906,0.272875,0.727125
3,1070.0,500.0,100.245729,-1.250480e+06,329.871754,124.868451,802.810702,-8.200846,0.076319,92.893445,...,2.885437,0.681833,0.128461,2.173573,0.000524,0.282845,95.537403,4.462597,0.981249,0.018751
4,1070.0,500.0,100.254660,-1.254981e+06,303.117275,85.489657,1172.710983,-8.200846,0.040477,96.236531,...,2.886185,0.682009,0.128495,2.147742,0.000993,0.282869,91.737706,8.262294,0.964465,0.035535

# Run an equilibrate calculation using the Green et al. (2025) thermodynamic model via MAGEMin

In [11]:
Eq_Green = ptt.equilibrate_multi(Model = "Green2025", bulk = bulk, 
                                 T_C = np.zeros(100) + 1070.0, 
                                 P_bar = 500.0, H2O_init = np.random.random(100)*10.0, 
                                 Fe3Fet_Liq = 0.15)

In [12]:
Eq_Green['All']

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),mass_per_mole_g/mol,eta_Pa.s,...,TiO2_Opx,Al2O3_Opx,Cr2O3_Opx,FeOt_Opx,MgO_Opx,CaO_Opx,Na2O_Opx,K2O_Opx,H2O_Opx,Fe3Fet_Opx
0,1070.0,500.0,100.0,-1.284655e+06,251.958037,43.589098,2294.151644,-9.789458,61.638993,176.977461,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1070.0,500.0,100.0,-1.276673e+06,294.853354,106.579548,938.266315,-9.851415,54.685148,182.869658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1070.0,500.0,100.0,-1.273362e+06,312.644446,132.638353,753.929750,-9.884067,52.240041,185.197400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1070.0,500.0,100.0,-1.276150e+06,297.680804,110.731455,903.085761,-9.857653,54.281025,183.597977,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1070.0,500.0,100.0,-1.279820e+06,277.983800,81.846334,1221.801821,-9.825611,57.223299,181.105783,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1070.0,500.0,100.0,-1.283519e+06,258.084501,52.605644,1900.936717,-9.798456,60.539096,178.266315,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,1070.0,500.0,100.0,-1.284937e+06,250.436171,41.347209,2418.542917,-9.787078,61.918369,176.813391,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,1070.0,500.0,100.0,-1.277608e+06,289.868830,99.284422,1007.207359,-9.846320,55.410834,182.461529,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1070.0,500.0,100.0,-1.283625e+06,257.507017,51.754578,1932.196203,-9.797206,60.641321,177.838583,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1070.0,500.0,100.0,-1.274090e+06,308.745026,126.937685,787.788116,-9.873810,52.756788,185.216638,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
Eq_Green['PhaseList']

0     Plag,Liq,Fl
1     Plag,Liq,Fl
2     Plag,Liq,Fl
3     Plag,Liq,Fl
4     Plag,Liq,Fl
         ...
95    Plag,Liq,Fl
96    Plag,Liq,Fl
97    Plag,Liq,Fl
98    Plag,Liq,Fl
99    Plag,Liq,Fl
Length: 100, dtype: str