In [1]:
import petthermotools as ptt 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

#### uncomment these two lines if alphaMELTS files are not added to your Python path - obviously you're have to change the file location
# import sys
# sys.path.append(r"/Users/gleesonm/Library/CloudStorage/GoogleDrive-gleesonm@berkeley.edu/My Drive/2022/GitHub/MELTS130beta/MacOS")

alphaMELTS for Python files successfully located.
If using the Green et al. (2025) or Weller et al. (2024) thermodynamic models please run `ptt.activate_petthermotools_env()` prior to any calculations.

In [2]:
bulk = {'SiO2': 53.93,
        'TiO2': 0.67,
        'Al2O3': 18.56,
        'FeOt': 8.5,
        'MnO': 0.21,
        'MgO': 3.96,
        'CaO': 9.16,
        'Na2O': 2.92,
        'K2O': 0.69,
        'P2O5': 0.13}

In [3]:
Combined = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.random.random(100)*200 + 920, # small bug, you have to make sure T_C is the correct size
                      P_bar = 2000, H2O_init = np.random.random(100)*10,
                      Fe3Fet_init = np.random.random(100)*0.15 + 0.05, cores = 2)

equilibrate_multi:   0%|          | 0/100 [00:00<?, ?it/s]

equilibrate_multi: 100/100 succeeded, 0 did not (a timeout is retried once at 2x timeout; a calculation error is not retried).

In [5]:
Combined['liquid1']

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,Cr2O3_Liq,Fe2O3_Liq,FeO_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq
0,57.040781,0.441425,15.101472,0.0,0.579407,6.365530,6.886877,0.266245,2.834758,7.058417,3.429111,0.973458,0.187112,5.722284,0.0,0.075701
1,54.214966,0.688974,16.063278,0.0,0.803549,7.842558,8.565585,0.233750,3.591455,7.937243,3.100015,0.801728,0.152774,4.569712,0.0,0.084411
2,69.611430,1.127355,11.689913,0.0,0.394428,3.055833,3.410737,1.216219,0.660366,5.545484,1.417307,3.038893,0.918966,1.323806,0.0,0.104055
3,52.649703,0.640382,17.040844,0.0,0.893584,7.535614,8.339655,0.214310,3.988565,8.456926,2.899176,0.702075,0.132668,4.846154,0.0,0.096412
4,55.500944,0.947805,15.278238,0.0,1.893258,8.992200,10.695741,0.300808,3.958288,7.765935,3.013330,0.928531,0.186214,1.234450,0.0,0.159273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,51.931825,0.645176,17.872329,0.0,1.204123,7.101602,8.185064,0.202219,3.813277,8.820610,2.811810,0.664435,0.125183,4.807410,0.0,0.132371
96,64.723955,0.567291,12.676693,0.0,0.449340,4.721867,5.126179,0.758417,1.195789,5.667497,3.015592,2.092605,0.469497,3.661458,0.0,0.078872
97,60.147381,0.372791,13.321086,0.0,0.282987,5.988629,6.243258,0.472349,1.569114,5.923363,3.870574,1.545092,0.310105,6.196530,0.0,0.040785
98,52.639716,0.539740,17.746770,0.0,0.996946,6.120335,7.017380,0.204976,3.717498,8.940846,2.850139,0.673492,0.126890,5.442653,0.0,0.127832
99,61.727712,0.311930,12.902692,0.0,0.317307,4.970705,5.256216,0.569636,1.401759,5.645708,3.776795,1.728870,0.352632,6.294255,0.0,0.054319

## Run the same calculation but suppress ALL solids (random H2O and CO2 contents)

In [5]:
NoSolids = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, P_bar = 500, H2O_init = np.random.random(100)*10, 
                                 CO2_init = np.random.random(100)*0.4, fO2_buffer = "NNO", fO2_offset = 1, Suppress = "All")

equilibrate_multi:   0%|          | 0/100 [00:00<?, ?it/s]

equilibrate_multi: 100/100 succeeded, 0 did not (a timeout is retried once at 2x timeout; a calculation error is not retried).

In [6]:
NoSolids['All'].head()

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),dVdP_cm^3/bar,SiO2_Liq,...,mu_h2o_Fl,mu_co2_Fl,mu0_h2o_Fl,mu0_co2_Fl,X_h2o_Fl,X_co2_Fl,H2O_Fl,CO2_Fl,X_H2O_mol_Fl,X_CO2_mol_Fl
0,1070.0,500.0,100.270525,-1.263319e+06,260.571832,38.946497,2574.571063,-8.200846,-0.000242,54.081619,...,-482319.911641,-655817.831035,-461368.421831,-653887.419297,0.158165,0.841835,7.141594,92.858406,0.158248,0.841752
1,1070.0,500.0,100.260362,-1.259068e+06,287.367227,61.530809,1629.433508,-8.200846,0.019004,53.277689,...,-461387.385083,-725796.866500,-461368.421831,-653887.419297,0.998304,0.001696,99.586591,0.413409,0.998305,0.001695
2,1070.0,500.0,100.269392,-1.262344e+06,262.818579,40.100652,2500.442946,-8.200846,0.000517,53.978501,...,-477569.232868,-656986.498461,-461368.421831,-653887.419297,0.241010,0.758990,11.503148,88.496852,0.241124,0.758876
3,1070.0,500.0,100.268318,-1.261982e+06,265.424426,40.537694,2473.458815,-8.200846,0.000659,53.823785,...,-472253.949779,-659375.006252,-461368.421831,-653887.419297,0.385076,0.614924,20.403679,79.596321,0.385224,0.614776
4,1070.0,500.0,100.247467,-1.251140e+06,324.399243,116.860537,857.838490,-8.200846,0.068961,53.296414,...,-461646.698467,-695907.815817,-461368.421831,-653887.419297,0.975439,0.024561,94.205200,5.794800,0.975453,0.024547

# Run an equilibrate calculation using the Green et al. (2025) thermodynamic model via MAGEMin

In [7]:
Eq_Green = ptt.equilibrate_multi(Model = "Green2025", bulk = bulk, 
                                 T_C = np.zeros(100) + 1070.0, 
                                 P_bar = 500.0, H2O_init = np.random.random(100)*10.0, 
                                 Fe3Fet_init = 0.15)

Julia environment detected.
Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

  Activating project at `~/.petthermotools_julia_env`

Using libMAGEMin.dylib from MAGEMin_jll

Computing 100 points... 100%|████████████████████████████| Time: 0:00:05

In [8]:
Eq_Green['All']

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),mass_per_mole_g/mol,eta_Pa.s,...,TiO2_Opx,Al2O3_Opx,Cr2O3_Opx,FeOt_Opx,MgO_Opx,CaO_Opx,Na2O_Opx,K2O_Opx,H2O_Opx,Fe3Fet_Opx
0,1070.0,500.0,100.0,-1.280380e+06,274.999376,77.471768,1290.792798,-9.810094,57.695474,180.813901,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1070.0,500.0,100.0,-1.271884e+06,320.581683,144.251467,693.233852,-9.883632,51.217412,185.922968,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1070.0,500.0,100.0,-1.276055e+06,298.221385,111.529948,896.620165,-9.844180,54.202864,183.885549,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1070.0,500.0,100.0,-1.277432e+06,290.832775,100.700621,993.042539,-9.832144,55.267326,183.008595,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1070.0,500.0,100.0,-1.281498e+06,269.002798,68.666318,1456.318068,-9.802041,58.671401,180.037457,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1070.0,500.0,100.0,-1.272518e+06,317.196199,139.307178,717.838103,-9.879461,51.647914,186.065820,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,1070.0,500.0,100.0,-1.278070e+06,287.377479,95.625964,1045.741088,-9.827700,55.780333,182.118747,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,1070.0,500.0,100.0,-1.278547e+06,284.836089,91.905174,1088.078018,-9.823921,56.162698,181.937291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1070.0,500.0,100.0,-1.284887e+06,250.767199,41.849811,2389.497034,-9.776633,61.854263,177.178035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1070.0,500.0,100.0,-1.280215e+06,275.866127,78.736777,1270.054525,-9.811947,57.557557,180.630238,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
Eq_Green['PhaseList']

0     Plag,Liq,Fl
1     Plag,Liq,Fl
2     Plag,Liq,Fl
3     Plag,Liq,Fl
4     Plag,Liq,Fl
         ...
95    Plag,Liq,Fl
96    Plag,Liq,Fl
97    Plag,Liq,Fl
98    Plag,Liq,Fl
99    Plag,Liq,Fl
Length: 100, dtype: str