In [1]:
import petthermotools as ptt 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

#### uncomment these two lines if alphaMELTS files are not added to your Python path - obviously you're have to change the file location
# import sys
# sys.path.append(r"/Users/gleesonm/Library/CloudStorage/GoogleDrive-gleesonm@berkeley.edu/My Drive/2022/GitHub/MELTS130beta/MacOS")

alphaMELTS for Python files successfully located.

In [3]:
# used to suppress MELTS outputs in MacOS systems (run twice)
import platform
if platform.system() == "Darwin":
    import sys
    import os
    sys.stdout = open(os.devnull, 'w')
    sys.stderr = open(os.devnull, 'w')

In [4]:
bulk = {'SiO2': 53.93,
        'TiO2': 0.67,
        'Al2O3': 18.56,
        'FeOt': 8.5,
        'MnO': 0.21,
        'MgO': 3.96,
        'CaO': 9.16,
        'Na2O': 2.92,
        'K2O': 0.69,
        'P2O5': 0.13}

In [5]:
Combined = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, # small bug, you have to make sure T_C is the correct size
                      P_bar = 2000, H2O_init = np.random.random(100)*10,
                      fO2_buffer="NNO", fO2_offset = 1)

In [6]:
Combined['liquid1']

,SiO2_Liq,TiO2_Liq,Al2O3_Liq,Cr2O3_Liq,Fe2O3_Liq,FeO_Liq,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq
0,54.112317,0.524508,18.086588,0.0,1.639285,3.835538,5.310555,0.210710,3.637430,9.190966,2.929871,0.692333,0.130439,5.010015,0.0,0.277752
1,61.599298,0.723521,14.718671,0.0,1.735229,4.001500,5.562847,0.401071,3.187140,7.025514,3.206806,1.208337,0.248282,1.944632,0.0,0.280674
2,54.682134,0.539455,18.192455,0.0,1.655681,3.850113,5.339884,0.213578,3.679818,9.253659,2.964172,0.701606,0.132215,4.135113,0.0,0.278989
3,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135
4,56.267610,0.566306,17.015121,0.0,1.719131,3.973527,5.520390,0.238054,4.060976,8.688993,3.101793,0.775920,0.147367,3.445201,0.0,0.280209
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,54.230001,0.527755,18.121967,0.0,1.642707,3.838400,5.316497,0.211168,3.644164,9.210955,2.936243,0.693838,0.130723,4.812077,0.0,0.278021
96,68.038835,1.378196,12.216633,0.0,1.538386,3.630852,5.015081,0.859674,1.603512,6.511303,1.747123,1.915357,0.532179,0.027950,0.0,0.276013
97,57.655186,0.587675,16.153945,0.0,1.752210,4.048384,5.625011,0.264704,4.290383,8.157952,3.172695,0.852922,0.163864,2.900080,0.0,0.280289
98,61.384720,0.713441,14.805950,0.0,1.737436,4.007062,5.570396,0.391648,3.247527,7.061790,3.224991,1.186406,0.242449,1.996581,0.0,0.280650
99,53.835613,0.516817,18.002623,0.0,1.630795,3.827442,5.294821,0.209632,3.621241,9.143968,2.914889,0.688792,0.129772,5.478412,0.0,0.277135

## Run the same calculation but suppress ALL solids (random H2O and CO2 contents)

In [7]:
NoSolids = ptt.equilibrate_multi(Model = "MELTSv1.2.0", bulk = bulk, T_C = np.zeros(100) + 1070, P_bar = 500, H2O_Liq = np.random.random(100)*10, 
                                 CO2_Liq = np.random.random(100)*0.4, fO2_buffer = "NNO", fO2_offset = 1, Suppress = "All")

In [8]:
NoSolids['All'].head()

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),dVdP_cm^3/bar,mass_g_Fl,...,FeOt_Liq,MnO_Liq,MgO_Liq,CaO_Liq,Na2O_Liq,K2O_Liq,P2O5_Liq,H2O_Liq,CO2_Liq,Fe3Fet_Liq
0,1070.0,500.0,100.248305,-1.252470e+06,322.963741,114.454789,875.876891,-8.200846,0.067051,6.362389,...,8.398093,0.207483,3.912545,9.050231,2.885008,0.681731,0.128442,2.188405,0.000254,0.282831
1,1070.0,500.0,100.263662,-1.260174e+06,277.198786,47.943880,2091.271327,-8.200846,0.006590,0.734539,...,8.408459,0.207740,3.917374,9.061401,2.888569,0.682573,0.128601,2.065358,0.002469,0.282946
2,1070.0,500.0,100.270432,-1.262481e+06,260.015877,40.030346,2504.860514,-8.200846,0.000693,0.219446,...,8.535182,0.210870,3.976413,9.197965,2.932102,0.692860,0.130539,0.569312,0.021192,0.284411
3,1070.0,500.0,100.250348,-1.253965e+06,317.352581,106.029237,945.497208,-8.200846,0.059521,5.576339,...,8.397050,0.207458,3.912059,9.049106,2.884650,0.681647,0.128426,2.200798,0.000027,0.282819
4,1070.0,500.0,100.246033,-1.251166e+06,329.592594,124.309966,806.419924,-8.200846,0.075977,7.221597,...,8.398268,0.207488,3.912626,9.050419,2.885068,0.681746,0.128445,2.186335,0.000292,0.282833

# Run an equilibrate calculation using the Green et al. (2025) thermodynamic model via MAGEMin

In [9]:
Eq_Green = ptt.equilibrate_multi(Model = "Green2025", bulk = bulk, 
                                 T_C = np.zeros(100) + 1070.0, 
                                 P_bar = 500.0, H2O_init = np.random.random(100)*10.0, 
                                 Fe3Fet_Liq = 0.15)

In [10]:
Eq_Green['All']

,T_C,P_bar,mass_g,H_J,S_J/K,V_cm^3,rho_kg/m^3,log10(fO2),mass_per_mole_g/mol,eta_Pa.s,...,TiO2_Opx,Al2O3_Opx,Cr2O3_Opx,FeOt_Opx,MgO_Opx,CaO_Opx,Na2O_Opx,K2O_Opx,H2O_Opx,Fe3Fet_Opx
0,1070.0,500.0,100.0,-1.275739e+06,299.891647,43.622125,2292.414673,-9.860996,53.969402,184.054613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1070.0,500.0,100.0,-1.285337e+06,247.717985,39.128784,2555.663368,-9.795460,62.439351,205.089714,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1070.0,500.0,100.0,-1.279470e+06,279.848667,41.860018,2388.914406,-9.828850,56.931563,181.102960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1070.0,500.0,100.0,-1.275037e+06,303.672613,43.967503,2274.407058,-9.867627,53.444548,184.402323,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1070.0,500.0,100.0,-1.277016e+06,293.035839,43.009755,2325.053936,-9.850408,54.947256,183.049447,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1070.0,500.0,100.0,-1.288591e+06,237.107520,37.304667,2680.629767,-9.479167,64.144985,3015.246615,...,0.077023,3.123473,0.0,21.86248,21.620951,1.956423,0.039956,0.0,0.0,0.086392
96,1070.0,500.0,100.0,-1.279848e+06,277.826508,41.688396,2398.749015,-9.825099,57.248261,180.942464,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,1070.0,500.0,100.0,-1.283026e+06,260.708462,40.261962,2483.733882,-9.801837,60.080817,178.245997,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,1070.0,500.0,100.0,-1.283072e+06,260.457698,40.241072,2485.023235,-9.802161,60.124549,178.117164,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,1070.0,500.0,100.0,-1.278262e+06,286.342353,42.422747,2357.225961,-9.838120,55.936841,182.201695,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
Eq_Green['PhaseList']

0         Fsp,Liq,Fl
1            Fsp,Liq
2         Fsp,Liq,Fl
3         Fsp,Liq,Fl
4         Fsp,Liq,Fl
           ...
95    Fsp,Ol,Liq,Opx
96        Fsp,Liq,Fl
97        Fsp,Liq,Fl
98        Fsp,Liq,Fl
99        Fsp,Liq,Fl
Length: 100, dtype: object